### ISSUE TITLE
Where can I download the installer?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [fizzyade/regex101#2]
I can't find the installer. Where can I download it?

**Comment by fizzyade** [comment]
I haven't generated installable binaries for it, what platform you want them for?  (Windows, macOS, Linux?)

**Comment by ogrishman** [comment]
I'm on Windows. Could you help to create an installer for it? Thank you in advance.

**Comment by fizzyade** [comment]
It’s 2am here at the moment, I will create an installer for you tomorrow and let you know when it’s available.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I'm on Windows. Thank you man! Have a good night!

**Comment by fizzyade** [comment]
Check releases, there is a Windows installer that I just created.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for your help!
